# -*- coding: utf-8 -*-
"""Lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12u5iEhKX9GC-R5pRNUi4UgaMFQieLzfo

Ex 1
"""

import math
r = float(input("enter circle radius? "))
area = math.pi * r * r
print("circle area =", round(area, 1))

"""Ex 2"""

c = float(input("enter the temperature in celsius? "))
f = c * 9 / 5 + 32
print(c, "(C) =", f, "(F)")

"""Ex 3"""

n = int(input("enter a number? "))
if n < 2:
    print(n, "is not a prime number")
else:
    prime = True
    for i in range(2, n):
        if n % i == 0:
            prime = False
            break
    if prime:
        print(n, "is a prime number")
    else:
        print(n, "is not a prime number")

"""Ex 4"""

n = int(input("enter a number? "))
total = 0
for i in range(1, n):
    if n % i == 0:
        total += i
if total == n:
    print(n, "is a perfect number")
else:
    print(n, "is not a perfect number")

"""Ex 5"""

colors = ["blue", "yelow", "black", "red", "white"]
color = input("what is your favorite color? ")
if color in colors:
    print("ur color is at index", colors.index(color), "in my list")
else:
    print("sorry, i could not find your color")

"""Ex 6"""

range1 = range(7)
range2 = range(1,11,3)
range3 = range(5,0)
range4 = range(4)
print("range1:", list(range1))
print("range2:", list(range2))
print("range3:", list(range3))
print

"""Ex 7"""

def remove_dollar_sign(s):
    return s.replace("$", "")
print(remove_dollar_sign("$1"))

"""Ex 8"""

def extract_even(l):
    result = []
    for x in l:
        if x % 2 == 0:
            result.append(x)
    return result

"""Ex 9"""

def factorial(n):
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result

"""Ex 10"""

def divisors(n):
    result = []

    for i in range(1, n + 1):
        if n % i == 0:
            result.append(i)

    return result

"""Ex 11"""

import math

x1 = float(input("Enter x1: "))
y1 = float(input("Enter y1: "))
x2 = float(input("Enter x2: "))
y2 = float(input("Enter y2: "))

distance = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)

print("Distance =", distance)

"""Ex 12"""

def rectangle(m, n):
    for i in range(m):
        for j in range(n):
            if i == 0 or i == m - 1 or j == 0 or j == n - 1:
                print("*", end=" ")
            else:
                print(" ", end=" ")
        print()

rectangle(4, 5)